project_id = "xnbiwocnyslsdrmezpdy"

[functions.chat]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.generate-image]
verify_jwt = true
